//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM_1Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public string Код { get; set; }
        public int Номер { get; set; }
        public string Артикул_товара { get; set; }
        public int Количество { get; set; }
        public System.DateTime Дата { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public int Код_пункта_выдачи { get; set; }
        public int Код_пользователя { get; set; }
        public int Код_получения { get; set; }
        public string Статус { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Пункт_выдачи Пункт_выдачи { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
