//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM_1Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public string Артикул { get; set; }
        public string Наименование_товара { get; set; }
        public string Единица_измерения { get; set; }
        public string Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string Категория_товара { get; set; }
        public string Действующая_скидка { get; set; }
        public string Количество { get; set; }
        public string Описание { get; set; }
        public string Фото { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
